# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mesh.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'mesh.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmesh.proto\"!\n\x05Shape\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\x0b\n\x03\x63ol\x18\x02 \x01(\r\"\xa3\x01\n\x04Mesh\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x0evertices_shape\x18\x02 \x01(\x0b\x32\x06.Shape\x12\x10\n\x08vertices\x18\x03 \x01(\x0c\x12\x1b\n\x0b\x66\x61\x63\x65s_shape\x18\x04 \x01(\x0b\x32\x06.Shape\x12\r\n\x05\x66\x61\x63\x65s\x18\x05 \x01(\x0c\x12\r\n\x05\x63olor\x18\x06 \x01(\x0c\x12\n\n\x02ka\x18\x07 \x01(\x02\x12\n\n\x02kd\x18\x08 \x01(\x02\x12\n\n\x02ks\x18\t \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mesh_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHAPE']._serialized_start=14
  _globals['_SHAPE']._serialized_end=47
  _globals['_MESH']._serialized_start=50
  _globals['_MESH']._serialized_end=213
# @@protoc_insertion_point(module_scope)
